/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyCard {
        "card": {cardId: number, isShown: boolean, isSolved: boolean, color: string};
        "try": number;
    }
    interface MyTable {
    }
}
export interface MyCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyCardElement;
}
declare global {
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    interface HTMLMyTableElement extends Components.MyTable, HTMLStencilElement {
    }
    var HTMLMyTableElement: {
        prototype: HTMLMyTableElement;
        new (): HTMLMyTableElement;
    };
    interface HTMLElementTagNameMap {
        "my-card": HTMLMyCardElement;
        "my-table": HTMLMyTableElement;
    }
}
declare namespace LocalJSX {
    interface MyCard {
        "card"?: {cardId: number, isShown: boolean, isSolved: boolean, color: string};
        "onShowEvent"?: (event: MyCardCustomEvent<any>) => void;
        "try"?: number;
    }
    interface MyTable {
    }
    interface IntrinsicElements {
        "my-card": MyCard;
        "my-table": MyTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-card": LocalJSX.MyCard & JSXBase.HTMLAttributes<HTMLMyCardElement>;
            "my-table": LocalJSX.MyTable & JSXBase.HTMLAttributes<HTMLMyTableElement>;
        }
    }
}
