/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyCard {
        "card": {cardId: number, isShown: boolean, solved: boolean, color: string};
        "try": number;
    }
    interface MyModal {
        "text": string;
    }
    interface MyTable {
    }
}
export interface MyCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyCardElement;
}
export interface MyModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyModalElement;
}
declare global {
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    interface HTMLMyModalElement extends Components.MyModal, HTMLStencilElement {
    }
    var HTMLMyModalElement: {
        prototype: HTMLMyModalElement;
        new (): HTMLMyModalElement;
    };
    interface HTMLMyTableElement extends Components.MyTable, HTMLStencilElement {
    }
    var HTMLMyTableElement: {
        prototype: HTMLMyTableElement;
        new (): HTMLMyTableElement;
    };
    interface HTMLElementTagNameMap {
        "my-card": HTMLMyCardElement;
        "my-modal": HTMLMyModalElement;
        "my-table": HTMLMyTableElement;
    }
}
declare namespace LocalJSX {
    interface MyCard {
        "card"?: {cardId: number, isShown: boolean, solved: boolean, color: string};
        "onShowEvent"?: (event: MyCardCustomEvent<any>) => void;
        "try"?: number;
    }
    interface MyModal {
        "onStartOver"?: (event: MyModalCustomEvent<any>) => void;
        "text"?: string;
    }
    interface MyTable {
    }
    interface IntrinsicElements {
        "my-card": MyCard;
        "my-modal": MyModal;
        "my-table": MyTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-card": LocalJSX.MyCard & JSXBase.HTMLAttributes<HTMLMyCardElement>;
            "my-modal": LocalJSX.MyModal & JSXBase.HTMLAttributes<HTMLMyModalElement>;
            "my-table": LocalJSX.MyTable & JSXBase.HTMLAttributes<HTMLMyTableElement>;
        }
    }
}
